(Write a function so that the columns of the output matrix are powers of the input
vector.
The order of the powers is determined by the increasing boolean argument. Specifically, when
increasing is False, the i-th output column is the input vector raised element-wise to the power
of N - i - 1.

HINT: Such a matrix with a geometric progression in each row is named for Alexandre-
Theophile Vandermonde)

In [4]:
#creating a matrix of output columnsbased on input vector(N)
import numpy as np
x=np.array([1,2,3,4,5])
N=5
matrix=np.column_stack([x**(N-i-1) for i in range(N)])
print(matrix)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [12]:
#Similar matrix is created using np.vander function in numpy
import numpy as np
x=np.array([1,2,3,4,5])
N=5
matrix1=np.vander(x,N,increasing=False)
print(matrix1)

[[  1   1   1   1   1]
 [ 16   8   4   2   1]
 [ 81  27   9   3   1]
 [256  64  16   4   1]
 [625 125  25   5   1]]


In [24]:
#Question: Write a function to find moving average in an array over a window:
#Test it over [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150] and window of 3.

def mov_avg_val(mylist, N):
    cumsum, moving_aves = [0], []
    for i, x in enumerate(mylist, 1):
        cumsum.append(cumsum[i-1] + x) 
        if i>=N:
            moving_ave = round(((cumsum[i] - cumsum[i-N])/N),2) 
            moving_aves.append(moving_ave) 
    print("Moving average values list: ", moving_aves)
    print("Length of the list l-N+1: ", len(moving_aves))


In [25]:
mylist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
N = 3

mov_avg_val(mylist,N)

Moving average values list:  [5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]
Length of the list l-N+1:  11
